name: Docker Caching

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ] 
  workflow_dispatch:
  
env:
  cache_image: mshekow/cache-comparison:buildcache


jobs:
  install-deps:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        # push: true
        target: dependencies 
        tags: user/app:latest
        cache-from: type=registry,ref=${{ env.cache_image }}
        cache-to: type=registry,ref=${{ env.cache_image }},mode=max

  test:
    runs-on: ubuntu-latest
    needs: install-deps
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        # push: true
        target: tests 
        tags: user/app:latest
        cache-from: type=registry,ref=${{ env.cache_image }}
        cache-to: type=registry,ref=${{ env.cache_image }},mode=max
        
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        # push: true
        target: build 
        tags: user/app:latest
        cache-from: type=registry,ref=${{ env.cache_image }}
        cache-to: type=registry,ref=${{ env.cache_image }},mode=max
    
