name: Node.js CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ] 
  workflow_dispatch:


jobs:
  install-deps:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 14
        cache: 'yarn'
    - run: yarn install --frozen-lockfile

  test:
    runs-on: ubuntu-latest
    needs: install-deps
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 14
        cache: 'yarn'
    - run: yarn install --frozen-lockfile
    - run: yarn test
    
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 14
        cache: 'yarn'
    - run: yarn install --frozen-lockfile
    - run: yarn build